###REGISTER
POST http://localhost:4520/user/register
Content-Type: application/json

{
    "userName":"Bob Kiongo",
    "email":"bobkiongo@gmail.com",
    "password":"12345678",
    "phone_no":"0711110000"
}


###login
POST http://localhost:4520/user/login
Content-Type: application/json

{
    "email":"9superbikes@gmail.com",
    "password":"12345678"
}

###getallUsers
GET http://localhost:4520/user/getallusers
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI5YTA1NTQzMC01YTcxLTQ2NDUtYjk0OS1kMzg3MzIyNDQyNjkiLCJ1c2VyTmFtZSI6IlNhbmRyYSBDaGVnZSIsImVtYWlsIjoiOXN1cGVyYmlrZXNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaXNEZWxldGVkIjpmYWxzZSwicmVzZXRQYXNzd29yZCI6ZmFsc2UsIldlbGNvbWVkIjpmYWxzZSwiaWF0IjoxNzAwNDEwODYzLCJleHAiOjE3MDA0OTcyNjN9.zjtLU1Rmy0vraIhOvPPGpokZpGqe7C8pE2Ux3TcLwYc


###checkuserdetails
GET http://localhost:4520/user/checkuserdetails
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI5YTA1NTQzMC01YTcxLTQ2NDUtYjk0OS1kMzg3MzIyNDQyNjkiLCJ1c2VyTmFtZSI6IlNhbmRyYSBDaGVnZSIsImVtYWlsIjoiOXN1cGVyYmlrZXNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaXNEZWxldGVkIjpmYWxzZSwicmVzZXRQYXNzd29yZCI6ZmFsc2UsIldlbGNvbWVkIjpmYWxzZSwiaWF0IjoxNzAwMzYwOTI1LCJleHAiOjE3MDA0NDczMjV9.UJvrDjQg66Y7Ul6iy4nn_XuNQLb6neYWVriio713odc

###getoneuser
GET http://localhost:4520/user/getoneuser
Content-Type: application/json

{
    "email": "michellewambui@gmail.com"
}

###updateuser
PUT http://localhost:4520/user/updateuser
Content-Type: application/json

{
    "userID":"1fb78ffa-d20a-4bdd-9323-7df7957c974a",
    "userName": "Caleb Baraka Kellah"
}

###deleteoneuser
DELETE http://localhost:4520/user/deleteuser/a6454caa-6295-4c59-ad31-7b4d4e5cfb15

###updatepassword
POST http://localhost:4520/user/updatepassword
Content-Type: application/json

{
    "email": "Annan@gmail.com",
    "password": "11112222"
}

###CREATE TOURS
POST http://localhost:4520/tour/addtour
Content-Type: application/json

{
    "imageUrl": "https://cdn.pixabay.com/photo/2016/09/08/13/58/desert-1654439_1280.jpg",
    "tourName": "Zanzibar",
    "tourDescription": "Travel to zanzibar",
    "tourPrice": "7000",
    "tourStartDate": "2023-12-12",
    "tourEndDateName": "2024-01-02",
    "tourCount":"20"
}
###GET ALL TOURS
GET http://localhost:4520/tour/getalltours
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI5YTA1NTQzMC01YTcxLTQ2NDUtYjk0OS1kMzg3MzIyNDQyNjkiLCJ1c2VyTmFtZSI6IlNhbmRyYSBDaGVnZSIsImVtYWlsIjoiOXN1cGVyYmlrZXNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaXNEZWxldGVkIjpmYWxzZSwicmVzZXRQYXNzd29yZCI6ZmFsc2UsIldlbGNvbWVkIjpmYWxzZSwiaWF0IjoxNzAwMTMxOTY2LCJleHAiOjE3MDAyMTgzNjZ9.etDW05XqmUBgDoayIWICNrY3LnHumbZ0gSlGwhejims

###GET ONE TOUR
POST http://localhost:4520/tour/gettour
Content-Type: application/json

{
    "tourID":"2cb0844c-0ca2-4141-80e2-6ea8e298f1b1"
}

###updateTour
Put http://localhost:4520/tour/updatetour
Content-Type: application/json

{   
    "tourID":"bbc627d2-33e4-41cd-9d5b-42f5673a3a92",
    "imageUrl": "https://cdn.pixabay.com/photo/2016/09/08/13/58/desert-1654439_1280.jpg",
    "tourName": "Kiambu National Park",
    "tourDescription": "Kiambu National Park",
    "tourPrice": "5000",
    "tourStartDate": "2023-12-12",
    "tourEndDateName": "2024-01-12",
    "tourCount":"20"
}

###DELETE TOUR
DELETE http://localhost:4520/tour/deletetour/2cb0844c-0ca2-4141-80e2-6ea8e298f1b1



###Addreview
POST http://localhost:4520/review/addreview
Content-Type: application/json

{
   "reviewContent":"Giraffe Manor is an exciting place to be",
    "userID":"ab4823e4-00ee-4d64-bad0-96533b2563f9",
    "tourID":"35096da1-4b4d-4b23-97bf-659fb9d6a3ff"
}
###GET ALL Reviews
GET http://localhost:4520/review/getallreviews
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI5YTA1NTQzMC01YTcxLTQ2NDUtYjk0OS1kMzg3MzIyNDQyNjkiLCJ1c2VyTmFtZSI6IlNhbmRyYSBDaGVnZSIsImVtYWlsIjoiOXN1cGVyYmlrZXNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaXNEZWxldGVkIjpmYWxzZSwicmVzZXRQYXNzd29yZCI6ZmFsc2UsIldlbGNvbWVkIjpmYWxzZSwiaWF0IjoxNzAwMTMxOTY2LCJleHAiOjE3MDAyMTgzNjZ9.etDW05XqmUBgDoayIWICNrY3LnHumbZ0gSlGwhejims

###GET ONE REVIEW
GET http://localhost:4520/review/getonereview
Content-Type: application/json

{
    "reviewID":"2fbc8dab-6322-4004-b1b6-bddfc7085b4b"
}

###updateReview
Put http://localhost:4520/review/updatereview
Content-Type: application/json

{   
    "reviewID":"5659aeec-793e-44fa-aef4-ff1f10530df4",
    "reviewContent": "Mombasa is a cool place to spend your holiday"
}

###DELETE REVIEW
DELETE http://localhost:4520/review/deletereview/5659aeec-793e-44fa-aef4-ff1f10530df4



###Add BOOKING
POST http://localhost:4520/booking/addbooking
Content-Type: application/json

{
    "tourID":"35096da1-4b4d-4b23-97bf-659fb9d6a3ff",
    "totalprice":"1000",
    "totalBookCount":"1",
    "userID":"18a0a01a-8239-4a56-b7ed-1cbf11610c9f"
    
}
###GET ALL BOOKINGS
GET http://localhost:4520/booking/getallbookings
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI5YTA1NTQzMC01YTcxLTQ2NDUtYjk0OS1kMzg3MzIyNDQyNjkiLCJ1c2VyTmFtZSI6IlNhbmRyYSBDaGVnZSIsImVtYWlsIjoiOXN1cGVyYmlrZXNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaXNEZWxldGVkIjpmYWxzZSwicmVzZXRQYXNzd29yZCI6ZmFsc2UsIldlbGNvbWVkIjpmYWxzZSwiaWF0IjoxNzAwMTMxOTY2LCJleHAiOjE3MDAyMTgzNjZ9.etDW05XqmUBgDoayIWICNrY3LnHumbZ0gSlGwhejims

###GET ONE BOOKING
GET http://localhost:4520/booking/getonebooking
Content-Type: application/json

{
    "bookID":"17137267-02a3-4e78-9aa6-71f6ab438d07"
}

###updatebooking
PUT http://localhost:4520/booking/updatebooking
Content-Type: application/json

{   
    "tourID":"35096da1-4b4d-4b23-97bf-659fb9d6a3ff",
    "totalprice":"50000",
    "totalBookCount":"10",
    "userID":"18a0a01a-8239-4a56-b7ed-1cbf11610c9f",
    "bookID": "ba861b72-497c-4429-8326-be6d19263862"
}

###DELETE BOOKING
DELETE http://localhost:4520/booking/deletebooking/a3f68e9a-089f-4552-85ad-d42394312053
