###
POST http://localhost:4520/user/register
Content-Type: application/json

{
    "userName":"Sandra Chege",
    "email":"9superbikes@gmail.com",
    "password":"30000001",
    "phone_no":"0700000001"
}


###login
POST http://localhost:4520/user/login
Content-Type: application/json

{
    "email":"sandraChege@gmail.com",
    "password":"360700000011"
}

###getallUsers
GET http://localhost:4520/user/getallusers
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI5ZjcyOTY4NC02YTIwLTQ3YTAtODAwOC0wZjNmY2UzODAxOWYiLCJ1c2VyTmFtZSI6IlNhbmRyYSBDaGVnZSIsImVtYWlsIjoic2FuZHJhQ2hlZ2VAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpc0RlbGV0ZWQiOmZhbHNlLCJXZWxjb21lZCI6ZmFsc2UsImlhdCI6MTcwMDA1ODY1MiwiZXhwIjoxNzAwMTQ1MDUyfQ.RZNgePxuzidoXCd1Heve8bg9ixUSBgUrdwaPt6iTJAA

###checkuserdetails
GET http://localhost:4520/user/checkuserdetails
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJjNWU2ODZkMC1lNWIxLTQwNTktOGUxMi0xZDU0MmIwNWVlNDEiLCJ1c2VyTmFtZSI6IlNhbmRyYSBjaGVnZSIsImVtYWlsIjoiOXN1cGVyYmlrZXNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiV2VsY29tZWQiOmZhbHNlLCJpYXQiOjE3MDAwNTA1MDQsImV4cCI6MTcwMDEzNjkwNH0.AX_K5Y0LIxIZTGffXRMoTX600l9VpOM0RsDpxsJUjy8

###getoneuser
GET http://localhost:4520/user/getoneuser
Content-Type: application/json

{
    "email": "9superbikes@gmail.com"
}

###updateuser
# POST http://localhost:4520/user/getoneuser
# Content-Type: application/json

# {
#     "userName": "Sandra Chege",
#     "phone_no":"0710000000"
# }

# ###deleteoneuser
DELETE http://localhost:4520/user/deleteuser/7aa06d43-f383-4625-af8b-3f83ffe4e50b

# ###updatepassword
# POST http://localhost:4500/user/updatepassword
# Content-Type: application/json

# {
#     "password": "12345678"
# }
# ######

# ####
# post http://localhost:4520/user/register
# Content-Type: application/json

# {
#     "userName":"Perez Annan",
#     "email":"perez@gmail.com",
#     "password":"30000023",
#     "phone_no":"0700000000"
# }
########
